[package]
name = "learn-rust"
version = "0.1.0"
edition = "2021"
default-run = "feistel"

[dependencies]
sha2 = "0.10.8"
anyhow = "1.0.89"

[[bin]]
name = "wc"
path = "src/wc.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[[bin]]
name = "feistel"
path = "src/feistel.rs"

